dar: proper error handling in full/incr backup script

diff --git a/modules/dar/templates/incr_backup.erb b/modules/dar/templates/incr_backup.erb
--- a/modules/dar/templates/incr_backup.erb
+++ b/modules/dar/templates/incr_backup.erb
@@ -31,9 +31,17 @@ echo
 echo "** Starting up backup [ $(date -R) ]"
 echo "** Incremental backup using dar (#$INCRNO) ..."
 dar -c "${BACKUP_NAME}_incr$INCRNO" -R / -A "$refbackup" -J "$key" $@
+rc="$?"
+if [ "$rc" -ne 0 -o "$rc" -ne 11 ] ; then
+  echo "** dar failed. Abort [ $(date -R) ]"
+  exit 1
+fi
 
 echo "** Copying backup to Google Cloud Storage ..."
 remote_name="${BACKUP_NAME}_incr$INCRNO.1.dar"
-gsutil -q cp "$remote_name" "$BACKUP_REMOTE"
+if ! gsutil -q cp "$remote_name" "$BACKUP_REMOTE" ; then
+  echo "** gsutil failed. Abort [ $(date -R) ]"
+  exit 1
+fi
 
 echo "** All done. [ $(date -R) ]"
